#!/bin/bash
gfortran -g hw_live.f90 -c
gfortran -g hw_live.o -L../ -lsimpledraw -lGL -lglfw -Wl,-rpath=`pwd`/.. -o f_live.out

gfortran -g hw.f90 -c
gfortran -g hw.o -L../ -lsimpledraw -lGL -lglfw -Wl,-rpath=`pwd`/.. -o f.out
